### PR TITLE
Template merge

### PR DESCRIPTION
**Pull request by kprist**
Not sure if this is the most correct way to merge the template changes, but it is correct I think. In the future I would however suggest we don't ask maintainers to merge changes from the template, and instead create a confluence page with implicit suggestions (like upgrading libraries, eslint, etc) so that each maintainer could apply those changes manually. The template repo should be kept as just that, a template for new services (however they may be in the remaining time, and of those of course any that rely on node and hapi etc.)

### CODE REVIEW

**Comment by kprist** [comment]
@rmeissn each repo should evolve on its own after being initialized using the template, that's what I'm saying. For example, there are many linter warnings left, which I would like to review at some later time, because I'm not sure if I will agree with the changes in the template eslint. So instead of just having a template to merge, I would prefer a page with some documentation/discussion about the changes in the template. It could be on github as well if it was easier, on the template repo.

**Comment by rmeissn** [comment]
According to some tips for Microservices ([see this book](http://shop.oreilly.com/product/0636920033158.do)), it is recommended to keep services with the same technology stack at the same library levels. So you can move developers between services easier, because they know at least about the base technologies and their base features and don't need to look into features of 3-5 different (for example) HAPI versions. + Service updates are maintained in a central way. If I remember right, it was also a recommendation of Netflix to have a template that is merged from time to time.
Shall we move this discussion to a Confluence page and invite other infrastructure Devs alike to discuss about the pros and cons?
Btw.: The Commit history of the microservice-template is kind of "What has been changed since the last update". We could also introduce releases (git tags) with a changelog on Github.

**Comment by kprist** [comment]
Books looks nice, thanks! From the contents alone I can see there a lot of other things we are not doing, probably if we did this template merge wouldn't be such a hassle. I was mainly concerned with the linting changes, as not all of those are suitable for the code base or code style of each service maintainer, I'm guessing ;).

**Comment by rmeissn** [comment]
Well, you don't need to adopt all those changes, if you think some don't fit for your service. It's just a recommendation ;)
Indeed, there is a lot more about microservices than what we do. But these topics are pretty hard to sell in our project.... especially if you want to introduce them before they are actually needed.

**Pull request merged**
